name: catbreeds_bloc
description: A application for cats breeds information with Flutter and BloC
  Pattern with Clean Architecture.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  card_loading: ^0.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.6
  go_router: ^8.0.1
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/languages/
